package me.pog5.anyscale.client.config;

import me.pog5.anyscale.client.AnyscaleClient;
import net.caffeinemc.mods.sodium.api.config.ConfigEntryPoint;
import net.caffeinemc.mods.sodium.api.config.StorageEventHandler;
import net.caffeinemc.mods.sodium.api.config.structure.ConfigBuilder;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;

public class ConfigGUIBuilder implements ConfigEntryPoint {
    private final AnyscaleConfig store = AnyscaleClient.config;
    private final StorageEventHandler handler = store::save;

    @Override
    public void registerConfigLate(ConfigBuilder builder) {
        builder.registerOwnModOptions()
                .setNonTintedIcon(Identifier.tryParse("anyscale:icon.png"))
                .addPage(builder.createOptionPage()
                        .setName(Component.literal("UI Scaling"))
                        .addOptionGroup(builder.createOptionGroup()
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "base_scale"))
                                        .setName(Component.literal("Base (Menu) Scale"))
                                        .setTooltip(Component.literal("This value is the base GUI scale, the same from General, except more detailed. All other values here are based on top of it. It gets divided by 100 (350 -> 3.5). Requires you to close the current menu and open it again to take effect."))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.base_scale = (float) value / 100, () -> (int) (store.base_scale * 100))
                                        .setDefaultValue(100)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                        .setRange(50, 500, 5)
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "inventory_scale"))
                                        .setName(Component.literal("Inventory Scale"))
                                        .setTooltip(Component.literal("This value controls the size of (Ender) Chests, Barrels, Hoppers, Inventories, etc... It gets divided by 100 (350 -> 3.5). Requires you to close the current menu and open it again to take effect."))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.menu_scale = (float) value / 100, () -> (int) (store.menu_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(50, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "playerlist_scale"))
                                        .setName(Component.literal("Player List (TAB) Scale"))
                                        .setTooltip(Component.literal("Player List (TAB) scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.playerlist_scale = (float) value / 100, () -> (int) (store.playerlist_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "scoreboard_scale"))
                                        .setName(Component.literal("Scoreboard Scale"))
                                        .setTooltip(Component.literal("Sidebar scoreboard scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.scoreboard_scale = (float) value / 100, () -> (int) (store.scoreboard_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "chat_scale"))
                                        .setName(Component.literal("Chat Scale"))
                                        .setTooltip(Component.literal("Chatbox and Chat messages scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.chat_scale = (float) value / 100, () -> (int) (store.chat_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "hotbar_scale"))
                                        .setName(Component.literal("Hotbar Scale"))
                                        .setTooltip(Component.literal("Hotbar scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.hotbar_scale = (float) value / 100, () -> (int) (store.hotbar_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "debug_scale"))
                                        .setName(Component.literal("F3 (Debug) Scale"))
                                        .setTooltip(Component.literal("Debug Menu scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.debug_scale = (float) value / 100, () -> (int) (store.debug_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "actionbar_scale"))
                                        .setName(Component.literal("Action Bar Scale"))
                                        .setTooltip(Component.literal("Action Bar scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.actionbar_scale = (float) value / 100, () -> (int) (store.actionbar_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createIntegerOption(Identifier.fromNamespaceAndPath("anyscale", "title_scale"))
                                        .setName(Component.literal("Title Text Scale"))
                                        .setTooltip(Component.literal("Title and Subtitle scaling, gets divided by 100 (350 -> 3.5)"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.title_scale = (float) value / 100, () -> (int) (store.title_scale * 100))
                                        .setDefaultValue(100)
                                        .setRange(0, 500, 5)
                                        .setValueFormatter((val) -> Component.nullToEmpty(String.format("%.2f", val / 100f)))
                                )
                                .addOption(builder.createBooleanOption(Identifier.fromNamespaceAndPath("anyscale", "inventory_disables_chat"))
                                        .setName(Component.literal("Hide chat in inventories"))
                                        .setTooltip(Component.literal("Hides chat messages when a inventory is open"))
                                        .setStorageHandler(handler)
                                        .setBinding((value) -> store.container_disables_chat = value, () -> store.container_disables_chat)
                                        .setDefaultValue(false)
                                )
                        )
                );
    }
}
